version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/app
      - ./data/chroma:/data/chroma
      - ./data:/app/data
    command: >
      bash -lc "
      python -m playwright install --with-deps &&
      pytest -q || true &&
      python -m iea.cli
      "
    depends_on:
      - pgvector

  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports: ["6024:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langchain"]
      interval: 5s
      timeout: 5s
      retries: 40
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
